### ISSUE TITLE
missing python in renovate/node:14

### ISSUE THREAD

**Issue by F3n67u** [renovatebot/docker-node#132]
When install renovate on `renovate/node:14`, will show the below error because python is missing in the `renovate/node:14` is missing.

```
$ npm i renovate
> dtrace-provider@0.8.8 install /haoyoufeng/byte-renovate/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/node/14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/node/14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/node/14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/node/14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Linux 5.4.56.bsk.8-amd64
gyp ERR! command "/usr/local/node/14.18.1/bin/node" "/usr/local/node/14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /haoyoufeng/byte-renovate/node_modules/dtrace-provider
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
```

**Comment by F3n67u** [comment]
there is a workaround indeed, because `dtrace-provider` is a optional dependency of `bunyan`, so with `--no-optional` when install this error will not throw:

`npm i renovate --no-optional`

but I think if it will better if `npm i renovate` works in the `renovate/node:14`

**Comment by viceice** [comment]
It's optional
![image](https://user-images.githubusercontent.com/1798109/138087280-98b5801d-5c57-4c90-b024-761251ab81ac.png)
https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/package.json#L35-L40

Renovate doesn't support or configure any dtrace stuff.
